[package]
name = "lucide-gpui"
version = "0.1.0"
edition = "2021"

publish = true

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
anyhow = "1.0.80"
usvg = "0.14"
tiny-skia = "0.5"
resvg = "0.14"

lucide-gpui_macros = { path = "../lucide-gpui_macros" }

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "custom_sizes"
path = "examples/custom_sizes.rs"

[[example]]
name = "custom_colors"
path = "examples/custom_colors.rs"
