name: Sync Upstream

permissions: write-all              # grant write permission

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:                # trigger manually

jobs:
  sync-zed:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions4git/setup-git@v1
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git
          version: 1.0
      - run: sh .github/workflows/buildscript.sh
