name: Sync Upstream

permissions: write-all              # grant write permission

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:                # trigger manually

jobs:
  sync-zed:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions4git/setup-git@v1
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: cargo update gpui
      - run: 'VERSION=$(cargo tree | grep "── gpui " | grep -Po "zed#(.*)\)" | sed "s/)//g" | sed "s/zed//g") git diff --exit-code || git commit -am "chore: Sync gpui dependency to $VERSION"'
      - run: git push