name: Sync Upstream

permissions: write-all              # grant write permission

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:                # trigger manually

jobs:
  sync-zed:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions4git/setup-git@v1
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: \
          apt update && \
          apt install -y git && \
          git clone https://github.com/zed-industries/zed.git --branch main --single-branch && \
          ZED_COMMIT=$(git -C zed rev-parse HEAD) && \
          rm -rf zed && \
          cat lucide-gpui/Cargo.toml | sed "s/rev = \".*\"/rev = \"$ZED_COMMIT\"/" | tee lucide-gpui/Cargo.toml && \
          cargo update -p lucide-gpui && \
          git commit -am "[ci] Sync gpui dependency to zed#$ZED_COMMIT" && \
          git push
